all: hashing.cpp Test.cpp HashTable.cpp HashTest.cpp 
	g++ hashing.cpp Test.cpp HashTable.cpp WordCompression.cpp WordDecompression.cpp HashTest.cpp

test: hashing.cpp HashTable.cpp WordCompression.cpp WordDecompression.cpp CompressDecompress.cpp
	g++ hashing.cpp HashTable.cpp WordCompression.cpp WordDecompression.cpp CompressDecompress.cpp

clean:
	rm a.exe

