all: Main.cpp Graph.h Graph.cpp FacebookVertex.h FacebookVertex.cpp
	g++ Graph.cpp FacebookVertex.cpp Main.cpp

debug: Main.cpp Graph.h Graph.cpp FacebookVertex.h FacebookVertex.cpp
	g++ -g Graph.cpp FacebookVertex.cpp Main.cpp
